#!/bin/bash
set -e

Flamingo(){
    bspcolor color --flamingo;
    exit
}

Mauve(){
    bspcolor color --mauve;
    exit
}

Pink(){
    bspcolor color --pink;
    exit
}

Maroon(){
    bspcolor color --maroon;
    exit
}

Red(){
    bspcolor color --red;
    exit
}

Peach(){
    bspcolor color --peach;
    exit
}

Yellow(){
    bspcolor color --yellow;
    exit
}

Green(){
    bspcolor color --green;
    exit
}

Teal(){
    bspcolor color --teal;
    exit
}

Blue(){
    bspcolor color --blue;
    exit
}

Sky(){
    bspcolor color --sky;
    exit
}

menu(){
sleep 0.1
echo "Color scheme change"
sleep 0.1
echo -e "
                1) Flamingo
                2) Mauve
                3) Pink
                4) Maroon
                5) Red
                6) Peach
                7) Yellow
                8) Green
                9) Teal
                10) Blue
                11) Sky
                
                q)    Cancel"
echo
echo -en "Choose An Option: "
	read option
	case $option in
		1) Flamingo ;;
		2) Mauve ;;
		3) Pink ;;
        4) Maroon ;;
        5) Red ;;
        6) Peach ;;
        7) Yellow ;;
        8) Green ;;
        9) Teal ;;
        10) Blue ;;
        11) Sky ;;
        q) exit ;;
        *) echo " \"$option\" Is Not A Valid Option"; sleep 1; menu ;;
	esac
}

menu
