#!/usr/bin/env bash

# WallpaperSet
RB='\e[5;31m' GB='\e[5;32m' Y='\e[1;33m' 
M='\e[1;35m' C='\e[1;36m' W='\e[1;37m' 
NC='\e[0m' CL='\ec' r='\e[0;31m' B='\e[0;34m'

case ${1} in
    *)   
        printf "${CL}${C}-${GB}-${NC}${C}- ${W}Select wallpaper. \n This process may take a few seconds! \n"
        for image in "${HOME}/.wallpaper/"*.*; do
            N="$((${N:-0}+1))"
            printf "${B}[${NC}${N}${B}] ${Cyan}$(grep -oE '[^/]+$' <<< "$image")\n"
            eval "image${N}=\$image"
        done
        printf "${C}-${GB}-${NC}${C}- ${W}Enter File Index ID ${M}[${NC}1-${N}${M}]${W}: ${NC}"
        read -r NUM; NUM="$(tr -dc '[:digit:]' <<< "$NUM")"
        if [[ "$NUM" -eq 0 || "$NUM" -gt "$N" ]]; then
            printf "${Y}[${RB}!${NC}${Y}] ${RB}Wrong selection\n" >&2
            exit 1
        else
            eval "IMG=\$image${NUM}"
            betterlockscreen -u "$IMG" &>/dev/null || exit 1
            bspwall
            cp $HOME/.cache/betterlockscreen/current/wall_resize.png /usr/share/wall/lightdm
            SELECTED="$(grep -oE '[^/]+$' <<< "$IMG")"
            printf "${C}[${GB}√${NC}${C}] ${W}Selected wallpaper: ${Green}${SELECTED}\n"
        fi
    ;;
esac

exit ${?}
